# Generated by Django 6.0.3 on 2026-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='age_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='age_min',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
