# Generated by Django 6.0.3 on 2026-09-13 07:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_course_import_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content_body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
