# Generated by Django 6.0.3 on 2026-09-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_alter_chapter_content_body_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=280, unique=True),
        ),
    ]
