# Generated by Django 6.1.1 on 2026-09-20 01:02

import core.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_alter_course_slug_alter_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.files.ParentNamedUploadPath('chapters/files', 'content')),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.files.ParentNamedUploadPath('courses/thumbnails', 'thumbnail')),
        ),
    ]
