# Generated by Django 6.0.3 on 2026-09-13 07:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_article_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full article body with rich-text formatting.'),
        ),
    ]
