# Generated by Django 6.1.1 on 2026-09-20 01:02

import core.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_sanitize_event_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.files.ParentNamedUploadPath('events/covers', 'cover')),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=core.utils.files.ParentNamedUploadPath('events/images', 'image')),
        ),
    ]
