# Generated by Django 6.1.1 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_cover_image_alter_eventimage_image"),
        ("programs", "0008_alter_program_banner_alter_project_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project this event or activity supports.",
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="events",
                to="programs.project",
            ),
        ),
    ]
