# Generated by Django 6.0.3 on 2026-04-04 12:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('programs', '0005_project_progress_percentage_project_raised_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('foundation', 'Foundation'), ('corporation', 'Corporation'), ('government', 'Government'), ('ngo', 'NGO / INGO'), ('multilateral', 'Multilateral Agency'), ('faith_based', 'Faith-Based Organization'), ('individual', 'High-Net-Worth Individual'), ('other', 'Other')], default='foundation', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='donors/logos/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='bronze', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lapsed', 'Lapsed'), ('prospect', 'Prospect'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text='List of thematic areas, e.g. ["Education", "Health"]')),
                ('first_funded_at', models.DateField(blank=True, help_text='Date of first grant/funding received.', null=True)),
                ('last_funded_at', models.DateField(blank=True, help_text='Date of most recent grant/funding received.', null=True)),
                ('total_funded', models.DecimalField(decimal_places=2, default=0, help_text='Total amount ever received from this donor (auto-updated).', max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('prefers_anonymous', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not public).')),
                ('relationship_owner', models.ForeignKey(blank=True, help_text='Staff member responsible for this donor relationship.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_donor_orgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donor_organizations',
                'ordering': ['-total_funded', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DonorContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('programme_officer', 'Programme Officer'), ('grants_manager', 'Grants Manager'), ('executive', 'Executive / Director'), ('finance', 'Finance Officer'), ('other', 'Other')], default='other', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this organization.')),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='donors.donororganization')),
            ],
            options={
                'db_table': 'donor_contacts',
                'ordering': ['-is_primary', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reference_code', models.CharField(blank=True, db_index=True, help_text='Internal or donor-assigned grant reference number.', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('funding_type', models.CharField(choices=[('project', 'Project-Based'), ('operational', 'Operational / General'), ('capacity', 'Capacity Building'), ('emergency', 'Emergency'), ('research', 'Research'), ('other', 'Other')], default='project', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('disbursed_date', models.DateField(blank=True, help_text='Date funds were actually received.', null=True)),
                ('reporting_deadline', models.DateField(blank=True, null=True)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='donors/agreements/')),
                ('report_submitted', models.BooleanField(default=False)),
                ('report_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_grants', to='donations.donationcampaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='donors.donorcontact')),
                ('donor_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='donors.donororganization')),
                ('internal_owner', models.ForeignKey(blank=True, help_text='Staff member who manages this grant internally.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_grants', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_grants', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_grants', to='programs.project')),
            ],
            options={
                'db_table': 'donor_grants',
                'ordering': ['-disbursed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('email', 'Email'), ('meeting', 'Meeting'), ('call', 'Phone Call'), ('report', 'Report Submitted'), ('visit', 'Site Visit'), ('event', 'Event / Conference'), ('proposal', 'Proposal Submitted'), ('other', 'Other')], default='email', max_length=15)),
                ('date', models.DateField()),
                ('summary', models.TextField(help_text='What was discussed / done.')),
                ('outcome', models.TextField(blank=True, help_text='Result or follow-up needed.')),
                ('next_action', models.TextField(blank=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='donors.donorcontact')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_engagements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='donors.donororganization')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='donors.grant')),
            ],
            options={
                'db_table': 'donor_engagements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donororganization',
            index=models.Index(fields=['status', 'tier'], name='donor_organ_status_599f39_idx'),
        ),
        migrations.AddIndex(
            model_name='donororganization',
            index=models.Index(fields=['type'], name='donor_organ_type_b2d550_idx'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['status', 'disbursed_date'], name='donor_grant_status_f3a3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['donor_organization', 'status'], name='donor_grant_donor_o_a23ec9_idx'),
        ),
    ]
