# Generated by Django 6.1.1 on 2026-09-20 01:02

import core.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donororganization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.files.ParentNamedUploadPath('donors/logos', 'logo')),
        ),
        migrations.AlterField(
            model_name='grant',
            name='agreement_document',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.files.ParentNamedUploadPath('donors/agreements', 'agreement')),
        ),
    ]
