# Generated by Django 6.1.1 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0002_alter_donororganization_logo_and_more"),
        ("organization", "0004_alter_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="donororganization",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization supported by this donor.",
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="donors",
                to="organization.organization",
            ),
        ),
    ]
