# Generated by Django 6.0.3 on 2026-03-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
