# Generated by Django 6.0.3 on 2026-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_project_cover_image_project_cover_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary shown in listing cards.', max_length=500),
        ),
    ]
