# Generated by Django 6.0.3 on 2026-03-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_project_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary shown in listing cards.', max_length=500),
        ),
    ]
