# Generated by Django 6.0.3 on 2026-03-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
