# Generated by Django 6.0.3 on 2026-09-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=280),
        ),
    ]
