# Generated by Django 6.1.1 on 2026-09-20 01:02

import core.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_program_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.files.ParentNamedUploadPath('programs/banners', 'banner')),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.files.ParentNamedUploadPath('projects/covers', 'cover')),
        ),
    ]
