# Generated by Django 6.1.1 on 2026-09-20 01:02

import core.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='If blank, the first image in the album is used as cover.', null=True, upload_to=core.utils.files.ParentNamedUploadPath('gallery/covers', 'cover')),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=core.utils.files.ParentNamedUploadPath('gallery/images', 'image')),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated smaller version.', null=True, upload_to=core.utils.files.ParentNamedUploadPath('gallery/thumbnails', 'thumbnail')),
        ),
    ]
