# Generated by Django 6.0.3 on 2026-09-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='slug',
            field=models.SlugField(max_length=280),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=280, unique=True),
        ),
    ]
