# Generated by Django 6.1.1 on 2026-09-20 01:02

import core.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_branch_slug_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.files.ParentNamedUploadPath('org/logos', 'logo')),
        ),
    ]
