"""
Seed the HOVUCA Comprehensive Sexuality Education (CSE) course
from the CSV generated by export_manual_to_csv.py.

Usage:
    python manage.py seed_cse_course

Or optionally:
    python manage.py seed_cse_course path/to/cse_manual.csv
"""

import csv
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from apps.elearning.models import Subject, Course, Module, Chapter
from apps.elearning.models.chapter import sanitize_chapter_body


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parents[3]
SOURCE_DIR = BASE_DIR / "data"
SOURCE_FILE = SOURCE_DIR / "cse_manual.csv"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_int(value, default=None):
    """
    Convert CSV values to integers.

    Empty strings and None return `default`.
    """
    if value is None:
        return default

    value = str(value).strip()

    if not value:
        return default

    return int(value)


def read_csv(csv_path):
    """Read the exported CSE CSV."""
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as file:
        return list(csv.DictReader(file))


def upsert(model, lookup, defaults):
    """
    Idempotent upsert: create if missing, otherwise diff against the
    existing row and only write fields that actually changed.

    Returns (instance, status) where status is one of
    "created", "updated", "unchanged".
    """
    instance = model.objects.filter(**lookup).first()

    if instance is None:
        instance = model.objects.create(**lookup, **defaults)
        return instance, "created"

    changed_fields = [
        field for field, value in defaults.items()
        if getattr(instance, field) != value
    ]

    if not changed_fields:
        return instance, "unchanged"

    for field in changed_fields:
        setattr(instance, field, defaults[field])
    instance.save(update_fields=changed_fields)

    return instance, "updated"


# ---------------------------------------------------------------------------
# Seeder
# ---------------------------------------------------------------------------

def seed(csv_path):
    rows = read_csv(csv_path)

    if not rows:
        print("CSV contains no rows.")
        return

    print()
    print("=" * 70)
    print("HOVUCA CSE COURSE SEED")
    print("=" * 70)
    print(f"Source: {csv_path}")
    print(f"Rows:   {len(rows)}")
    print()

    first = rows[0]

    # -----------------------------------------------------------------------
    # Subject
    # -----------------------------------------------------------------------

    subject, status = upsert(
        Subject,
        lookup={"slug": first["subject_slug"]},
        defaults={
            "name": first["subject_name"],
            "is_active": True,
        },
    )

    print(f"{status.upper()} Subject: {subject.name}")

    # -----------------------------------------------------------------------
    # Course
    # -----------------------------------------------------------------------

    import_key = first.get("course_import_key") or "hovuca-cse-manual-v1"
    course = Course.all_objects.filter(import_key=import_key).first()
    status = "unchanged"

    if course is None:
        candidates = Course.objects.filter(subject=subject)
        course = candidates.filter(slug=first["course_slug"]).first()
        if course is None and candidates.count() == 1:
            course = candidates.first()

        if course is None:
            course = Course.objects.create(
                import_key=import_key,
                subject=subject,
                title=first["course_title"],
                slug=first["course_slug"],
                description=first["description"],
                difficulty=first["course_difficulty"],
                is_published=True,
                is_free=True,
            )
            status = "created"
        else:
            course.import_key = import_key
            course.save(update_fields=["import_key"])
            status = "adopted"

    course, content_status = upsert(
        Course,
        lookup={"pk": course.pk},
        defaults={
            "subject": subject,
            "description": first["description"],
            "difficulty": first["course_difficulty"],
            "is_published": True,
            "is_free": True,
        },
    )
    if status == "unchanged":
        status = content_status

    print(f"{status.upper()} Course: {course.title}")

    print()

    # -----------------------------------------------------------------------
    # Modules
    # -----------------------------------------------------------------------

    module_cache = {}

    modules_created = 0
    modules_updated = 0
    modules_unchanged = 0

    chapters_created = 0
    chapters_updated = 0
    chapters_unchanged = 0

    total_duration_minutes = 0

    for row in rows:

        module_order = parse_int(row["module_order"])

        # Module.order is unique within a course, so it is the safest
        # identifier for lookup.
        module_key = module_order

        if module_key not in module_cache:

            age_min = parse_int(
                row.get("module_age_min"),
                default=10,
            )

            age_max = parse_int(
                row.get("module_age_max"),
                default=None,
            )

            module, status = upsert(
                Module,
                lookup={"course": course, "order": module_order},
                defaults={
                    "title": row["module_title"],
                    "description": row["module_description"],
                    "age_min": age_min,
                    "age_max": age_max,
                },
            )

            module_cache[module_key] = module

            if status == "created":
                modules_created += 1
            elif status == "updated":
                modules_updated += 1
            else:
                modules_unchanged += 1

            age_label = (
                f"{age_min}-{age_max}"
                if age_max is not None
                else f"{age_min}+"
            )

            print(
                f"{status.upper()} Module {module_order}: "
                f"{module.title} [{age_label}]"
            )

        else:
            module = module_cache[module_key]

        # -------------------------------------------------------------------
        # Chapter
        # -------------------------------------------------------------------

        chapter_order = parse_int(row["chapter_order"])

        duration_minutes = parse_int(
            row.get("duration_minutes"),
            default=0,
        )

        chapter, status = upsert(
            Chapter,
            lookup={"module": module, "order": chapter_order},
            defaults={
                "title": row["chapter_title"],
                "content_type": row.get("content_type") or "text",
                "content_body": sanitize_chapter_body(row.get("content_body") or ""),
                "duration_minutes": duration_minutes,
            },
        )

        total_duration_minutes += duration_minutes

        if status == "created":
            chapters_created += 1
            marker = "+"
        elif status == "updated":
            chapters_updated += 1
            marker = "~"
        else:
            chapters_unchanged += 1
            marker = "="

        print(
            f"    {marker} Chapter {chapter_order}: "
            f"{chapter.title} "
            f"({duration_minutes} min)"
        )

    # -----------------------------------------------------------------------
    # Update course estimated duration
    # -----------------------------------------------------------------------

    # estimated_hours is a PositiveSmallIntegerField, so round the chapter
    # duration up to the nearest whole hour.
    estimated_hours = (
        (total_duration_minutes + 59) // 60
        if total_duration_minutes
        else 0
    )

    if course.estimated_hours != estimated_hours:
        course.estimated_hours = estimated_hours
        course.save(update_fields=["estimated_hours"])

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------

    print()
    print("=" * 70)
    print("SEED COMPLETE")
    print("=" * 70)

    print(f"Subject:             {subject.name}")
    print(f"Course:              {course.title}")
    print(f"Estimated duration:  {estimated_hours} hours")
    print()

    print(f"Modules created:     {modules_created}")
    print(f"Modules updated:     {modules_updated}")
    print(f"Modules unchanged:   {modules_unchanged}")
    print(f"Modules total:       {len(module_cache)}")
    print()

    print(f"Chapters created:    {chapters_created}")
    print(f"Chapters updated:    {chapters_updated}")
    print(f"Chapters unchanged:  {chapters_unchanged}")
    print(f"Chapters total:      {chapters_created + chapters_updated + chapters_unchanged}")
    print()

    print("CSE course is published and ready to use.")


# ---------------------------------------------------------------------------
# Django management command
# ---------------------------------------------------------------------------

class Command(BaseCommand):
    help = "Idempotently seed the HOVUCA CSE course from the exported manual CSV."

    def add_arguments(self, parser):
        parser.add_argument("csv", nargs="?", type=Path, default=SOURCE_FILE)

    def handle(self, *args, **options):
        csv_path = options["csv"]
        if not csv_path.is_absolute():
            csv_path = BASE_DIR / csv_path

        if not csv_path.is_file():
            raise CommandError(
                f"CSE CSV file not found: {csv_path}. "
                "Generate it with scripts/course/export_manual_to_csv.py first."
            )

        seed(csv_path)
