# Generated by Django 6.0.3 on 2026-09-15 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField()),
                ('interests', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('hours_per_week', models.PositiveSmallIntegerField()),
                ('motivation', models.TextField()),
                ('contact_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'volunteer_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
