# Generated by Django 6.0.3 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("level", models.CharField(db_index=True, max_length=16)),
                ("logger", models.CharField(db_index=True, max_length=255)),
                ("message", models.TextField()),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("traceback", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "application log",
                "verbose_name_plural": "application logs",
                "db_table": "core_application_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["level", "created_at"], name="core_applic_level_1dac3f_idx"),
                    models.Index(fields=["logger", "created_at"], name="core_applic_logger_f695b2_idx"),
                ],
            },
        ),
    ]
