# Generated by Django 6.0.3 on 2026-09-15 11:23

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPaymentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=40)),
                ('bank_currency', models.CharField(default='XAF', max_length=3)),
                ('bank_instructions', models.TextField(blank=True)),
                ('paypal_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('campay_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https'])])),
            ],
            options={
                'verbose_name': 'Donation payment settings',
                'verbose_name_plural': 'Donation payment settings',
            },
        ),
    ]
